# Generated by Django 5.1.7 on 2026-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ragdocument_appruntimeconfig_childconsent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appruntimeconfig',
            name='key',
            field=models.CharField(choices=[('llm_provider', 'LLM Provider'), ('llm_base_url', 'LLM Base URL'), ('openai_model', 'OpenAI Model'), ('openai_api_key', 'OpenAI API Key'), ('system_prompt', 'System Prompt'), ('user_prompt_template', 'User Prompt Template'), ('child_system_prompt', 'Child System Prompt'), ('child_user_prompt_template', 'Child User Prompt Template')], max_length=64, unique=True),
        ),
    ]
