# Generated by Django 5.1.7 on 2026-03-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appruntimeconfig_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='childtodo',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
